name: Practice
# run-name: ${{ github.event.head_commit.message }} by @${{ github.actor }}
on:
  push:
  #   paths:
  #     - '**.js'
  #   branches:
  #   tags:
  workflow_dispatch:
  # schedule:
    # - cron: '0/10 * * * *' # –∑–∞–ø—É—Å–∫ –∫–∞–∂–¥—ã–µ 10 –º–∏–Ω—É—Ç
    # - cron: '55 6 9 2 MON' # –∑–∞–ø—É—Å–∫ –≤ –ø–æ–Ω–µ–¥–µ–ª—å–Ω–∏–∫ 2 —Ñ–µ–≤—Ä–∞–ª—è, 6:55 UTC time
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: |
          echo "üïí Current UTC time: $(date -u)"