name: Practice
on:
  workflow_dispatch:
  push:
jobs:
  job1: &base_job 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world"
          echo "Yo"

  job2: *base_job # Reuse the entire job configuration