name: test
on:
  workflow_run: 
    workflows: ["Practice"]
    branches-ignore:
      - "dev"
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: |
          echo "Hello"